### ISSUE TITLE
URLTitle: Several issues

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/kvirc-scripts#14]
- What about https?
- Can we do this without triggering the File Transfer manager coming up all the time?
- Can we do this on hover instead of right click?

I get some pretty buggy behaviour when hovering/clicking:

http://i.imgur.com/PmBNIIp.gifv

**Comment by un1versal** [comment]
works just fine here.

**Comment by Stanzilla** [comment]
Oh, my bad, you have to right click the link, I thought it works on hover.

**Comment by un1versal** [comment]
The behavior you see is normal, there's a delay between right clicking where things need to be fetched and then displayed.

@AndrioCelos to get a better reply for the other questions. (I think not really though)

**Comment by AndrioCelos** [comment]
Hi @Stanzilla; thanks for your report.

Your picture looks like the old default popup script is still active. The script was recently modified to reflect a change to KVIrc's default script (https://github.com/kvirc/KVIrc/commit/ac1e4d82c9daa040af03330507ff6ee7eb77b654). If you're running an older script, mine won't correctly disable the old event handler. You can disable it yourself in the Event Editor, or using the following command:
`/eventctl -d OnURLLinkPopupRequest "URL popup"`

I chose to show the File Transfers window, because it allows you to see the error message if the download fails, and the target URL of a redirect. You can skip it by opening the `URLTitle` event handler (of the `OnURLLinkPopupRequest` event), and changing `-w=m` to `-w=h`.

`http.asyncGet`, which this script uses, supports HTTPS just fine. As for hovering, I'm not aware of any way that currently exists in KVIrc, to run scripts on hovering over a link.

**Comment by un1versal** [comment]
@AndrioCelos 

Re: https://github.com/kvirc/KVIrc/commit/ac1e4d82c9daa040af03330507ff6ee7eb77b654 URL Popup to -> URLpopup

1 If you remove the handler by deleting it
2 close the event editor
3 execute the code below on script tester you can see what KVIrc does to the space plain as day.

```
event(OnURLLinkPopupRequest,URL popup) { popup.show urlpopup $0 }
```

1 Now open the Event editor 
2 Navigate to and expand OnURLLinkPopupRequest and see URL Popup (with space) All good right?
3 Now select the Handler and the select the event OnURLLinkPopupRequest again --> **magic. space gone in front of your very eyes**

Now remove handler again. and close event editor and re-add it like above

1 run  `/eventctl -d OnURLLinkPopupRequest "URL popup"` this goes ok 
2 select handler again and then OnURLLinkPopupRequest until space is gone
3 now enable handler `/eventctl -e OnURLLinkPopupRequest "URL popup"`

also works ok///

Running this script with original  `/eventctl -d OnURLLinkPopupRequest "URL popup"` you get a warning... as you know... very weird...

#### Conclusion for warning when you run the original script and this behaiviour: bug!

You can run  `/eventctl -d OnURLLinkPopupRequest "URLpopup"` and `/eventctl -d OnURLLinkPopupRequest "URLpopup"` **manually** on the Handler with/without space and it works, so ive idea except the warning (**I know its a warning** not **error**) makes no sense to me.

**Comment by un1versal** [comment]
re event disabler:
fixed the oopsie in https://github.com/kvirc/kvirc-scripts/commit/b0c624f381ce17eafa740b4483095bfd7c93cac9

Also added a comment explaining why on the disable command, the handler name is best left within quotes, without quotes you get a warning and wont work if the handler has space in name. probably part of weird bug type thing.

sorry Andrio.

**Comment by un1versal** [comment]
@AndrioCelos can this be closed or is there something to do here?

**Comment by AndrioCelos** [comment]
There aren't any problems that I'm aware of...
