### ISSUE TITLE
[Licencing] KVIrc Scripts / Themes - other 3rd party contribs to standalone repos.

### ISSUE THREAD

**Issue by un1versal** [kvirc/kvirc-scripts#5]
The below is not to make contributions difficult, But should be considered/discussed ironed out and implemented. This is following this discussion at https://github.com/kvirc/kvirc-scripts/issues/4

We should include a **notice** on the Scripts and Themes repos **readme** (and wherever else applicable) a default license that any contributions made where a license is absent, instead fallback to the default project specified lic.

Reading https://github.com/blog/1964-license-usage-on-github-com seems appropriate

**Applying default license if one isn't supplied:** e.g. https://www.shadertoy.com/terms does this.

I would suggest for themes and scripts, the default license should be as permissive as possible including no link-back. please suggest one.

Now the problem is the older than sin scripts and themes that dont have any licenses exist already and this must be handled in some way and addressed appropriately.

I suggest these are moved to a branch in same repo and labeled accordingly by readme: These themes were unlicensed by original author, if you're the author please resubmit the works under a specific license to main repo blablabla

Please discuss. ionic?

**Comment by Ionic** [comment]
Sounds good.

What everybody has to understand is that this is not meant to make contributor lives more difficult, but to protect the project from legal issues due to malevolent behavior.

If everything is properly licensed (including permission to modify, redistribute etc. already existing resources), the project is legally secured from IP claims.

I recommend the FSF page for selecting licenses: https://www.gnu.org/licenses/license-list.en.html

GPL-compatibility is generally good for source code contributions.

Artwork etc. should be licensed under an artistic license (not the "Artistic" license, but these listed under https://www.gnu.org/licenses/license-list.en.html#OtherLicenses)
"Creative Commons Attribution 4.0 license" sounds okay, but any free license applicable to artwork will be good.

All contributions that currently lack an explicit should be re-licensed retrospectively. I assume that the original authors just forgot to add a license and meant to use a free license - but we need explicit clearance from the people involved. Luckily there is a commit log and everything...
Without a clear license, this code, artwork and even documentation must be interpreted as proprietary.

**Comment by un1versal** [comment]
I suggest this type of readme customized for this repo https://github.com/uNiversaI/kvirc-themes/tree/Read-it-and-wheep

**Comment by pragmaware** [comment]
All the scripts in kvirc-scripts and themes in kvirc-themes were previously in the single kvirc svn, which had a single license: GPL. Everyone who submitted stuff in there implicitly accepted that license and that's what I'd use for the kvirc-scripts and kvirc-themes module (unless a subdirectory has a special license on its own).

**Comment by un1versal** [comment]
Excellent, that clears up a great deal and make intentions clear then and the direction the readmes will take also simpler to construct.

closing soon as I make the readmes.
